### ISSUE TITLE
Sleep not Working on PaperMc 1.16.4

### ISSUE THREAD

**Issue by Vadrome** [ArVdC/TimeManager#9]
Sleeping doesn't set the time accordingly. 
```
> [K[01:04:18 INFO]: Vadrome issued server command: /tm checkconfig
> [K[01:04:33 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m [0;31;1mToo late... morning might never come.[m
> [K[01:05:17 INFO]: Vadrome issued server command: /tm set sleep true
> [K[01:05:17 INFO]: [TimeManager] The world mc16paper 'sync' option was forced to false in order to allow players to sleep until the dawn.
> [K[01:05:17 INFO]: [TimeManager] It is allowed to sleep until the dawn in the world mc16paper.
> [K[01:05:17 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m The world [0;33;1mmc16paper[0;36;1m will now use the asynchronous decrease speed scheduler.[m
> [K[01:05:21 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Player [0;33;1mVadrome[0;36;1m is sleeping now (1/100 ticks).[m
> [K[01:05:26 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Sleep time is almost reached (99/100 ticks).[m
> [K[01:05:26 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Achieved ! (100/100 ticks) Now waiting for the morning.[m
> [K[01:05:26 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m The gamerule [0;33;1mdoDaylightCycle[0;36;1m is now set to [0;31;1mfalse[0;36;1m for the world [0;33;1mmc16paper[0;36;1m.[m
> [K[01:05:26 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m [0;31;1mToo late... morning might never come.[m
> > > [K[01:06:27 INFO]: Vadrome issued server command: /tm set speed 5
> [K[01:06:27 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m The gamerule [0;33;1mdoDaylightCycle[0;36;1m is now set to [0;32;1mtrue[0;36;1m for the world [0;33;1mmc16paper[0;36;1m.[m
> [K[01:06:27 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m If necessary, launch the scheduler corresponding to the asked speed value.[m
> [K[01:06:27 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m The world [0;33;1mmc16paper[0;36;1m will now use the asynchronous increase speed scheduler.[m
> [K[01:06:27 INFO]: [TimeManager] The speed of the world mc16paper is now multiplied by 5.0.
> [K[01:06:27 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m The gamerule [0;33;1mdoDaylightCycle[0;36;1m is now set to [0;32;1mtrue[0;36;1m for the world [0;33;1mmc16paper[0;36;1m.[m
> [K[01:06:27 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m The world [0;33;1mmc16paper[0;36;1m will now use the asynchronous increase speed scheduler.[m
> [K[01:06:39 INFO]: Vadrome issued server command: /tm set speed 8
> [K[01:06:39 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m The gamerule [0;33;1mdoDaylightCycle[0;36;1m is now set to [0;32;1mtrue[0;36;1m for the world [0;33;1mmc16paper[0;36;1m.[m
> [K[01:06:39 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m If necessary, launch the scheduler corresponding to the asked speed value.[m
> [K[01:06:39 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m The world [0;33;1mmc16paper[0;36;1m will now use the asynchronous increase speed scheduler.[m
> [K[01:06:39 INFO]: [TimeManager] The speed of the world mc16paper is now multiplied by 8.0.
> [K[01:06:56 INFO]: Vadrome issued server command: /tm set speed 10
> [K[01:06:56 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m The gamerule [0;33;1mdoDaylightCycle[0;36;1m is now set to [0;32;1mtrue[0;36;1m for the world [0;33;1mmc16paper[0;36;1m.[m
> [K[01:06:56 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m If necessary, launch the scheduler corresponding to the asked speed value.[m
> [K[01:06:56 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m The world [0;33;1mmc16paper[0;36;1m will now use the asynchronous increase speed scheduler.[m
> [K[01:06:56 INFO]: [TimeManager] The speed of the world mc16paper is now multiplied by 10.0.
> [K[01:07:44 INFO]: Vadrome issued server command: /tm set speed .265
> [K[01:07:44 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m The gamerule [0;33;1mdoDaylightCycle[0;36;1m is now set to [0;31;1mfalse[0;36;1m for the world [0;33;1mmc16paper[0;36;1m.[m
> [K[01:07:44 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m If necessary, launch the scheduler corresponding to the asked speed value.[m
> [K[01:07:44 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m The world [0;33;1mmc16paper[0;36;1m will now use the asynchronous decrease speed scheduler.[m
> [K[01:07:44 INFO]: [TimeManager] The speed of the world mc16paper is now multiplied by 0.265.
> [K[01:07:44 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m The gamerule [0;33;1mdoDaylightCycle[0;36;1m is now set to [0;31;1mfalse[0;36;1m for the world [0;33;1mmc16paper[0;36;1m.[m
> [K[01:07:44 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m The world [0;33;1mmc16paper[0;36;1m will now use the asynchronous decrease speed scheduler.[m
> [K[01:07:52 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Player [0;33;1mVadrome[0;36;1m is sleeping now (1/100 ticks).[m
> [K[01:07:57 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Sleep time is almost reached (99/100 ticks).[m
> [K[01:07:57 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Achieved ! (100/100 ticks) Now waiting for the morning.[m
> [K[01:07:57 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m The gamerule [0;33;1mdoDaylightCycle[0;36;1m is now set to [0;31;1mfalse[0;36;1m for the world [0;33;1mmc16paper[0;36;1m.[m
> [K[01:07:57 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m [0;31;1mToo late... morning might never come.[m
> [K[01:08:40 INFO]: Vadrome issued server command: /now
> [K[01:08:40 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13681[0;36;1m" was converted to "[0;33;1m19:40:51[0;36;1m".[m
> [K[01:08:42 INFO]: Vadrome issued server command: /now
> [K[01:08:42 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13693[0;36;1m" was converted to "[0;33;1m19:41:34[0;36;1m".[m
> [K[01:08:42 INFO]: Vadrome issued server command: /now
> [K[01:08:42 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13701[0;36;1m" was converted to "[0;33;1m19:42:03[0;36;1m".[m
> [K[01:08:43 INFO]: Vadrome issued server command: /now
> [K[01:08:43 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13709[0;36;1m" was converted to "[0;33;1m19:42:32[0;36;1m".[m
> [K[01:08:44 INFO]: Vadrome issued server command: /now
> [K[01:08:44 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13717[0;36;1m" was converted to "[0;33;1m19:43:01[0;36;1m".[m
> [K[01:08:45 INFO]: Vadrome issued server command: /now
> [K[01:08:45 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13725[0;36;1m" was converted to "[0;33;1m19:43:30[0;36;1m".[m
> [K[01:08:45 INFO]: Vadrome issued server command: /now
> [K[01:08:45 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13733[0;36;1m" was converted to "[0;33;1m19:43:58[0;36;1m".[m
> [K[01:08:46 INFO]: Vadrome issued server command: /now
> [K[01:08:46 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13737[0;36;1m" was converted to "[0;33;1m19:44:13[0;36;1m".[m
> [K[01:08:46 INFO]: Vadrome issued server command: /now
> [K[01:08:46 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13741[0;36;1m" was converted to "[0;33;1m19:44:27[0;36;1m".[m
> [K[01:08:47 INFO]: Vadrome issued server command: /now
> [K[01:08:47 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13749[0;36;1m" was converted to "[0;33;1m19:44:56[0;36;1m".[m
> [K[01:08:48 INFO]: Vadrome issued server command: /now
> [K[01:08:48 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13753[0;36;1m" was converted to "[0;33;1m19:45:10[0;36;1m".[m
> [K[01:08:48 INFO]: Vadrome issued server command: /now
> [K[01:08:48 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13761[0;36;1m" was converted to "[0;33;1m19:45:39[0;36;1m".[m
> [K[01:08:49 INFO]: Vadrome issued server command: /now
> [K[01:08:49 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13765[0;36;1m" was converted to "[0;33;1m19:45:54[0;36;1m".[m
> [K[01:08:49 INFO]: Vadrome issued server command: /now
> [K[01:08:49 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13773[0;36;1m" was converted to "[0;33;1m19:46:22[0;36;1m".[m
> [K[01:08:50 INFO]: Vadrome issued server command: /now
> [K[01:08:50 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13777[0;36;1m" was converted to "[0;33;1m19:46:37[0;36;1m".[m
> [K[01:08:51 INFO]: Vadrome issued server command: /now
> [K[01:08:51 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13785[0;36;1m" was converted to "[0;33;1m19:47:06[0;36;1m".[m
> [K[01:08:51 INFO]: Vadrome issued server command: /now
> [K[01:08:51 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13789[0;36;1m" was converted to "[0;33;1m19:47:20[0;36;1m".[m
> [K[01:08:52 INFO]: Vadrome issued server command: /now
> [K[01:08:52 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13797[0;36;1m" was converted to "[0;33;1m19:47:49[0;36;1m".[m
> [K[01:08:53 INFO]: Vadrome issued server command: /now
> [K[01:08:53 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13805[0;36;1m" was converted to "[0;33;1m19:48:18[0;36;1m".[m
> [K[01:08:53 INFO]: Vadrome issued server command: /now
> [K[01:08:53 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13811[0;36;1m" was converted to "[0;33;1m19:48:39[0;36;1m".[m
> [K[01:08:54 INFO]: Vadrome issued server command: /now
> [K[01:08:54 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13821[0;36;1m" was converted to "[0;33;1m19:49:15[0;36;1m".[m
> [K[01:08:55 INFO]: Vadrome issued server command: /now
> [K[01:08:55 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13829[0;36;1m" was converted to "[0;33;1m19:49:44[0;36;1m".[m
> [K[01:08:56 INFO]: Vadrome issued server command: /now
> [K[01:08:56 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13837[0;36;1m" was converted to "[0;33;1m19:50:13[0;36;1m".[m
> [K[01:08:57 INFO]: Vadrome issued server command: /now
> [K[01:08:57 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13845[0;36;1m" was converted to "[0;33;1m19:50:42[0;36;1m".[m
> [K[01:08:58 INFO]: Vadrome issued server command: /now
> [K[01:08:58 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13853[0;36;1m" was converted to "[0;33;1m19:51:10[0;36;1m".[m
> [K[01:08:58 INFO]: Vadrome issued server command: /now
> [K[01:08:58 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13861[0;36;1m" was converted to "[0;33;1m19:51:39[0;36;1m".[m
> [K[01:08:59 INFO]: Vadrome issued server command: /now
> [K[01:08:59 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13869[0;36;1m" was converted to "[0;33;1m19:52:08[0;36;1m".[m
> [K[01:09:00 INFO]: Vadrome issued server command: /now
> [K[01:09:00 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13877[0;36;1m" was converted to "[0;33;1m19:52:37[0;36;1m".[m
> [K[01:09:01 INFO]: Vadrome issued server command: /now
> [K[01:09:01 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13889[0;36;1m" was converted to "[0;33;1m19:53:20[0;36;1m".[m
> [K[01:09:02 INFO]: Vadrome issued server command: /now
> [K[01:09:02 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13897[0;36;1m" was converted to "[0;33;1m19:53:49[0;36;1m".[m
> [K[01:09:03 INFO]: Vadrome issued server command: /now
> [K[01:09:03 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13905[0;36;1m" was converted to "[0;33;1m19:54:18[0;36;1m".[m
> [K[01:09:04 INFO]: Vadrome issued server command: /now
> [K[01:09:04 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13915[0;36;1m" was converted to "[0;33;1m19:54:54[0;36;1m".[m
> [K[01:09:05 INFO]: Vadrome issued server command: /now
> [K[01:09:05 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13925[0;36;1m" was converted to "[0;33;1m19:55:30[0;36;1m".[m
> [K[01:09:06 INFO]: Vadrome issued server command: /now
> [K[01:09:06 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13933[0;36;1m" was converted to "[0;33;1m19:55:58[0;36;1m".[m
> [K[01:09:07 INFO]: Vadrome issued server command: /now
> [K[01:09:07 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13941[0;36;1m" was converted to "[0;33;1m19:56:27[0;36;1m".[m
> [K[01:09:07 INFO]: Vadrome issued server command: /now
> [K[01:09:07 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13949[0;36;1m" was converted to "[0;33;1m19:56:56[0;36;1m".[m
> [K[01:09:08 INFO]: Vadrome issued server command: /now
> [K[01:09:08 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13959[0;36;1m" was converted to "[0;33;1m19:57:32[0;36;1m".[m
> [K[01:09:09 INFO]: Vadrome issued server command: /now
> [K[01:09:09 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13967[0;36;1m" was converted to "[0;33;1m19:58:01[0;36;1m".[m
> [K[01:09:10 INFO]: Vadrome issued server command: /now
> [K[01:09:10 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13975[0;36;1m" was converted to "[0;33;1m19:58:30[0;36;1m".[m
> [K[01:09:11 INFO]: Vadrome issued server command: /now
> [K[01:09:11 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13985[0;36;1m" was converted to "[0;33;1m19:59:06[0;36;1m".[m
> [K[01:09:11 INFO]: Vadrome issued server command: /now
> [K[01:09:11 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m13993[0;36;1m" was converted to "[0;33;1m19:59:34[0;36;1m".[m
> [K[01:09:12 INFO]: Vadrome issued server command: /now
> [K[01:09:12 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m14001[0;36;1m" was converted to "[0;33;1m20:00:03[0;36;1m".[m
> [K[01:09:13 INFO]: Vadrome issued server command: /now
> [K[01:09:13 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m14009[0;36;1m" was converted to "[0;33;1m20:00:32[0;36;1m".[m
> [K[01:09:14 INFO]: Vadrome issued server command: /now
> [K[01:09:14 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m14017[0;36;1m" was converted to "[0;33;1m20:01:01[0;36;1m".[m
> [K[01:09:15 INFO]: Vadrome issued server command: /now
> [K[01:09:15 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m14021[0;36;1m" was converted to "[0;33;1m20:01:15[0;36;1m".[m
> [K[01:09:15 INFO]: Vadrome issued server command: /now
> [K[01:09:15 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m14029[0;36;1m" was converted to "[0;33;1m20:01:44[0;36;1m".[m
> [K[01:09:16 INFO]: Vadrome issued server command: /now
> [K[01:09:16 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m14037[0;36;1m" was converted to "[0;33;1m20:02:13[0;36;1m".[m
> [K[01:09:17 INFO]: Vadrome issued server command: /now
> [K[01:09:17 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m14045[0;36;1m" was converted to "[0;33;1m20:02:42[0;36;1m".[m
> [K[01:09:17 INFO]: Vadrome issued server command: /now
> [K[01:09:17 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m14053[0;36;1m" was converted to "[0;33;1m20:03:10[0;36;1m".[m
> [K[01:09:18 INFO]: Vadrome issued server command: /now
> [K[01:09:18 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m14059[0;36;1m" was converted to "[0;33;1m20:03:32[0;36;1m".[m
> [K[01:09:19 INFO]: Vadrome issued server command: /now
> [K[01:09:19 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m14065[0;36;1m" was converted to "[0;33;1m20:03:54[0;36;1m".[m
> [K[01:09:20 INFO]: Vadrome issued server command: /now
> [K[01:09:20 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m14073[0;36;1m" was converted to "[0;33;1m20:04:22[0;36;1m".[m
> [K[01:09:21 INFO]: Vadrome issued server command: /now
> [K[01:09:21 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m14081[0;36;1m" was converted to "[0;33;1m20:04:51[0;36;1m".[m
> [K[01:09:28 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Player [0;33;1mVadrome[0;36;1m is sleeping now (1/100 ticks).[m
> [K[01:09:33 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Sleep time is almost reached (99/100 ticks).[m
> [K[01:09:33 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Achieved ! (100/100 ticks) Now waiting for the morning.[m
> [K[01:09:33 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m The gamerule [0;33;1mdoDaylightCycle[0;36;1m is now set to [0;31;1mfalse[0;36;1m for the world [0;33;1mmc16paper[0;36;1m.[m
> [K[01:09:33 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m [0;31;1mToo late... morning might never come.[m
> [K[01:10:30 INFO]: Vadrome issued server command: /gamerule doDaylightCycle true
> [K[01:10:30 INFO]: [0;37m[3m[Vadrome: Gamerule doDaylightCycle is now set to: true][m
> [K[01:10:35 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Player [0;33;1mVadrome[0;36;1m is sleeping now (1/100 ticks).[m
> [K[01:10:40 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Sleep time is almost reached (99/100 ticks).[m
> [K[01:10:40 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Achieved ! (100/100 ticks) Now waiting for the morning.[m
> [K[01:10:40 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m The gamerule [0;33;1mdoDaylightCycle[0;36;1m is now set to [0;31;1mfalse[0;36;1m for the world [0;33;1mmc16paper[0;36;1m.[m
> [K[01:10:40 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m [0;31;1mToo late... morning might never come.[m
> stopave-all[K[7Dtop[Kave-all[K[7Dtop[Kave-all[K[7Dtop[Kave-all[K[7Dtop[Kave-all[K[7Dtop[K [Kstopave-all[K[7Dtop[Kave-all[K[7Dtop[Kave-all[K[K[0 1:11:25 INFO]: Vadrome issued server command: /now
> save-all[K[01:11:25 INFO]: [0;30;1m[21m[[0;33;1m[21mTimeManager[0;30;1m[21m][0;36;1m Given tick "[0;33;1m15536[0;36;1m" was converted to "[0;33;1m21:32:09[0;36;1m".[m
```
It's the only plugin installed. 
[config.txt](https://github.com/ArVdC/TimeManager/files/6026056/config.txt)

**Comment by ArVdC** [comment]
Hi,
Thanks for reporting this issue.
The next update (v1.4.2) should fix this sleep problem. I should publish it this evening.

**Comment by ArVdC** [comment]
Hope this will work fine now. Could you please confirm that ?
[https://github.com/ArVdC/TimeManager/releases/tag/v1.4.2](https://github.com/ArVdC/TimeManager/releases/tag/v1.4.2)

**Comment by Vadrome** [comment]
Still the same Problem, anything I might be doing wrong / can do to avoid this ?

```
[23:07:51 INFO]: Running delayed init tasks
[23:07:51 INFO]: Done (5.078s)! For help, type "help"
[23:07:51 INFO]: Timings Reset
[23:07:51 INFO]: [TimeManager] The server's initial tick was get from the config.yml.
[23:07:51 INFO]: [TimeManager] The server's initial tick is #1719079 (23:52:33 UTC).
[23:07:51 INFO]: [TimeManager] The server's current tick is #1593426 (22:07:51 UTC).
[23:07:51 INFO]: [TimeManager] The world mc16paper had its time resynchronized to the server time
[23:07:51 INFO]: [TimeManager] Resync: Calculation of [actualTime] for world mc16paper:
[23:07:51 INFO]: [TimeManager] [elapsedTime] = ([currentServerTick] - [initialTick]) % [ticksInOneDay] = (1593426 - 1719079) % 24000 = -5653 restrained to one day = 18347
[23:07:51 INFO]: [TimeManager] [adjustedElapsedTime] = [elapsedTime] * [speedModifier] = 18347 * 0.265 = 4861.955
[23:07:51 INFO]: [TimeManager] [actualTime] = [worldStartAt] + [adjustedElapsedTime] = 0 + 4861.955 = 4861.955 restrained to one day = tick #4861
[23:07:51 INFO]: [TimeManager] The gamerule doDaylightCycle is now set to false for the world mc16paper.
[23:07:51 INFO]: [TimeManager] Given tick "0" was converted to "06:00:00".
[23:07:51 INFO]: [TimeManager] Given tick "4861" was converted to "10:51:39".
[23:07:51 INFO]: [TimeManager] The world mc16paper is running since 80 whole day(s) (0001-03-22).
[23:07:51 INFO]: [TimeManager] The world mc16paper starts at 06:00:00 (+0 ticks).
[23:07:51 INFO]: [TimeManager] The world mc16paper's current time is 10:51:39 (#4861).
[23:07:51 INFO]: [TimeManager] The world mc16paper's current speed is 0.265.
[23:07:51 INFO]: [TimeManager] The world mc16paper will now use the asynchronous decrease speed scheduler.
[23:07:51 INFO]: [TimeManager] All worlds have been syncronized to the server time. If you want to keep them synchronized, set their 'sync' option to true.
[23:07:56 INFO]: [TimeManager] Last version on bukkit/curse is 1.4.1 and you are running the 1.4.2
[23:07:56 INFO]: [TimeManager] No update was found, you are running the latest version.
[23:07:58 INFO]: UUID of player Vadrome is 54e45318-763d-4936-ac09-5cdc964e7d76
[23:07:59 INFO]: Vadrome joined the game
[23:07:59 INFO]: Vadrome[/92.104.104.77:55216] logged in with entity id 253 at ([mc16paper]-1104.9121767486943, 89.0, 45.990983363149105)
[23:08:07 INFO]: Vadrome issued server command: /now
[23:08:07 INFO]: [TimeManager] Given tick "4941" was converted to "10:56:27".
[23:08:12 INFO]: Vadrome issued server command: /tm set time night
[23:08:12 INFO]: [TimeManager] The world mc16paper will now use the asynchronous decrease speed scheduler.
[23:08:12 INFO]: [TimeManager] The gamerule doDaylightCycle is now set to false for the world mc16paper.
[23:08:12 INFO]: [TimeManager] Given tick "13000" was converted to "19:00:00".
[23:08:12 INFO]: [TimeManager] The current time of the world mc16paper is now set to tick #13000 (19:00:00).
[23:08:14 INFO]: [TimeManager] Player Vadrome is sleeping now (1/100 ticks).
[23:08:19 INFO]: [TimeManager] Sleep time is almost reached (99/100 ticks).
[23:08:19 INFO]: [TimeManager] Achieved ! (100/100 ticks) Now waiting for the morning.
[23:08:19 INFO]: [TimeManager] The gamerule doDaylightCycle is now set to false for the world mc16paper.
[23:08:44 INFO]: [TimeManager] Too late...  morning might never come.
[23:08:49 INFO]: Vadrome issued server command: /now
[23:08:49 INFO]: [TimeManager] Given tick "13184" was converted to "19:11:02".
```

**Comment by ArVdC** [comment]
Maybe I have an idea. I'll check this tomorrow. Until then could you try with another value of refreshRate ?

**Comment by Vadrome** [comment]
I did a bit of testing with `/tm set speed`
Any speed value greater or equal to 1 works. Anything below 1 doesn't

**Comment by ArVdC** [comment]
I actualised the file, I think it's fixed.
[https://github.com/ArVdC/TimeManager/releases/tag/v1.4.2](https://github.com/ArVdC/TimeManager/releases/tag/v1.4.2)

**Comment by Vadrome** [comment]
It works now, thx
